### ISSUE TITLE
[Task] Implement the Lenra OAuth module to register/login into Lenra

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/client-common#82]
Implement the Lenra OAuth module to register/login into lenra using the `authorization code flow WITH PKCE`.

Use a existing library like flutter [oauth2_client](https://pub.dev/packages/oauth2_client)

**Comment by jonas-martinez** [comment]
Test on Android/Desktop

**Comment by jonas-martinez** [comment]
Remove the "checkAuthenticated" guard to use a Widget instead. The widget would be situated just above the navigator and will check if the user is authenticated. To make sure that the authentication status is regularly checked, we should trigger the widget if an API request ends with a "Authentication failed" error.

**Comment by jonas-martinez** [comment]
It seems that it does not work on Desktop and Mobile because the redirection is done on http but there is nothing that corresponds to that. 

See these 3 links to fix Linux, Windows, IOS, macos and Android
https://stackoverflow.com/questions/68716993/google-microsoft-oauth2-login-flow-flutter-desktop-macos-windows-linux/68716994#68716994
https://stackoverflow.com/questions/65458903/socketexception-connection-failed-os-error-operation-not-permitted-errno-1
https://stackoverflow.com/questions/11485271/google-oauth-2-authorization-error-redirect-uri-mismatch
